/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'ashishw' at '17/1/16 4:35 PM' with Gradle 2.2.1
 *
 * @author ashishw, @date 17/1/16 4:35 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
