/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'ashishw' at '17/1/16 4:35 PM' with Gradle 2.2.1
 *
 * @author ashishw, @date 17/1/16 4:35 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
